name: Push Docker Image To DockerHub and Github Package

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}

          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          tags: v1
          repository: php1301/doanwebbe
          push: true
      - name: Build and push Docker images To DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: v1
          repository: phucpham1301/doanweb
          push: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}